Modes observer
micro-ROS/system_modes pull request #68
Opened 2021-03-31 09:59 UTC by norro

Introduces a modes observer class that

- can be configured to monitor an arbitrary number of nodes and systems for their states and modes. To do so it
  - initially queries the getState and getMode services of monitored entities
  - after that continuously monitors ../transition_event and ../mode_event topics of monitored entities
- caches the states+modes of monitored entities locally for fast local access

The mode observer is supposed to be instantiated by+inside a ROS 2 node.

https://github.com/micro-ROS/system_modes/issues/66

2021-04-06 08:48 UTC, nielsvd requested changes
Check one open question.

2021-04-06 08:48 UTC, nielsvd commented on system_modes/include/system_modes/mode_observer.hpp
> +  ModeObserver(const ModeObserver &) = delete;
Is there a particular reason why you want to delete the copy constructor? I don't see why it's not possible to copy the observer.

2021-04-06 09:02 UTC, norro commented on system_modes/include/system_modes/mode_observer.hpp
> +  ModeObserver(const ModeObserver &) = delete;
No particular reason and you're right, there isn't really a good reason to prevent copying. :+1:

2021-04-06 15:17 UTC, nielsvd reviewed
see questions.

2021-04-06 15:17 UTC, nielsvd commented on system_modes/src/system_modes/mode_observer.cpp
> +    return StateAndMode();
What does this default to? Is it possible to recognize that the `get()` was unsuccessful? From the code it seems to be the default string and int initializations?

2021-04-06 15:17 UTC, nielsvd commented on system_modes/src/system_modes/mode_observer.cpp
> +  cache_[part_name] = StateAndMode();
Same question here as for the `get()` return value. Can we recognize when the initial requests were unsuccessful?

2021-04-07 06:10 UTC, norro commented on system_modes/src/system_modes/mode_observer.cpp
> +    return StateAndMode();
`at()`, on the cache, `std::map`, will throw an `out_of_range` exception when asking for a part that was not observed, yet. 
What do you prefer?
1. Catching the exception and logging it.
2. Same as 1. but also rethrowing the exception.
3. Don't handle the exception here so that you can catch and handle it outside.

Currently I am sort of doing 1., but I agree, should probably be 2. or 3. instead.

2021-04-07 06:30 UTC, nielsvd commented on system_modes/src/system_modes/mode_observer.cpp
> +    return StateAndMode();
My point is rather related to `StateAndMode` and not so much how you have implemented the `get()` routine; here, and on line 71 you initialize the return value / observed part by the default `StateAndMode`. I was wondering what these defaults are. Is it possible to programmatically detect whether this `StateAndMode` are the result of an unsuccessful observation? It seems to be a case where `std::optional` is appropriate, but perhaps not desired because it is not present in `c++14`.

2021-04-07 08:22 UTC, norro commented on system_modes/src/system_modes/mode_observer.cpp
> +    return StateAndMode();
The StateAndMode that is returned in case of an exception is of _unknown_ state and can now conveniently be tested for it, see https://github.com/micro-ROS/system_modes/blob/feature/modes-observer/system_modes/include/system_modes/mode_impl.hpp#L94-L97

2021-04-07 08:22 UTC, norro commented on system_modes/src/system_modes/mode_observer.cpp
> +  cache_[part_name] = StateAndMode();
Same as above.

2021-04-07 08:37 UTC, nielsvd approved these changes

2021-04-07 09:37 UTC, merged