Changed affiliation of Arne Nordmann to none/private
micro-ROS/system_modes pull request #92
Opened 2022-05-21 19:05 UTC by norro

Signed-off-by: Arne Nordmann <github@norro.de>

2022-05-21 19:10 UTC, ralph-lange commented
Note that there is a setup.py, which needs also to be updated (just search the whole repo for your old e-mail address.). Not sure whether two maintainers can be listed there. If not, then use your name and e-mail as first maintainer, please.

2022-05-21 19:11 UTC, ralph-lange requested changes

2022-05-21 19:11 UTC, ralph-lange commented on NOTICE
> +    Arne Nordmann <github@norro.de>
```suggestion
Arne Nordmann <github@norro.de>
```
No need for 'none'.

2022-05-22 18:42 UTC, norro commented
There doesn't seem to be an agreed way how to add multiple maintainers to setup.py that is not confusing pypi and the like. So I just went with my name there.

2022-05-23 05:32 UTC, ralph-lange approved these changes
LGTM

2022-05-23 08:51 UTC, merged